elasticsearch-data:
  image: 'alpine'
  command: '/bin/true'
  volumes:
    - '/data/elasticsearch:/usr/share/elasticsearch/data'
elasticsearch:
  image: elk/elasticsearch
  ports:
    - "9200:9200"
logstash:
  image: elk/logstash
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  ports:
    - "5000:5000"
    - "5514:5514"
  links:
    - elasticsearch
kibana:
  image: elk/kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
